# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[versions]
assertj = "3.26.3"
awaitility = "4.2.1"
caffeine = "2.9.3"
dorisConnector = "26.0.0"
errorProne = "2.10.0"
errorPronePlugin = "3.1.0"
googleJavaFormat = "1.22.0"
gravitino = "1.3.0"
guava = "32.1.3-jre"
junit = "5.11.4"
mockito = "5.14.2"
mysql = "8.0.33"
scala = "2.12.18"
spark = "3.5.8"
spotless = "6.25.0"
testcontainers = "1.21.4"
ratPlugin = "0.8.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
doris-spark-connector = { module = "org.apache.doris:spark-doris-connector-spark-3.5", version.ref = "dorisConnector" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorProne" }
gravitino-api = { module = "org.apache.gravitino:gravitino-api", version.ref = "gravitino" }
gravitino-catalog-common = { module = "org.apache.gravitino:gravitino-catalog-common", version.ref = "gravitino" }
gravitino-catalog-jdbc-common = { module = "org.apache.gravitino:gravitino-catalog-jdbc-common", version.ref = "gravitino" }
gravitino-catalog-jdbc-doris = { module = "org.apache.gravitino:gravitino-catalog-jdbc-doris", version.ref = "gravitino" }
gravitino-client = { module = "org.apache.gravitino:gravitino-client-java", version.ref = "gravitino" }
gravitino-client-runtime = { module = "org.apache.gravitino:gravitino-client-java-runtime", version.ref = "gravitino" }
gravitino-common = { module = "org.apache.gravitino:gravitino-common", version.ref = "gravitino" }
gravitino-core = { module = "org.apache.gravitino:gravitino-core", version.ref = "gravitino" }
gravitino-server = { module = "org.apache.gravitino:gravitino-server", version.ref = "gravitino" }
gravitino-server-common = { module = "org.apache.gravitino:gravitino-server-common", version.ref = "gravitino" }
gravitino-spark-common = { module = "org.apache.gravitino:gravitino-spark-common", version.ref = "gravitino" }
gravitino-spark35 = { module = "org.apache.gravitino:gravitino-spark-3.5_2.12", version.ref = "gravitino" }
gravitino-spark-runtime35 = { module = "org.apache.gravitino:gravitino-spark-connector-runtime-3.5_2.12", version.ref = "gravitino" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mysql-driver = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
scala-library = { module = "org.scala-lang:scala-library", version.ref = "scala" }
spark-catalyst = { module = "org.apache.spark:spark-catalyst_2.12", version.ref = "spark" }
spark-core = { module = "org.apache.spark:spark-core_2.12", version.ref = "spark" }
spark-sql = { module = "org.apache.spark:spark-sql_2.12", version.ref = "spark" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorPronePlugin" }
rat = { id = "org.nosphere.apache.rat", version.ref = "ratPlugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
